[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cneural_net"
version = "0.01"

[tool.setuptools.packages.find]
where = []
include = []
exclude = []
namespaces = false
